### ISSUE TITLE
add cd-rom files

### ISSUE THREAD

**Issue by Stromweld** [Parallels/packer-plugin-parallels#102]
#### Community Note

Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request.
If you are interested in working on this issue or have submitted a pull request, please leave a comment.

#### Description

Add cdrom-files similar to floppy-files for efi and secure boot systems like windows 11 on arm that doesn't recognize the floppy-disk for autounattended. This would also match other similar providers like virtualbox, vmware, and qemu iso builders.

#### Use Case(s)

windows autounattend.xml file for iso builders on modern efi and secure boot configurations

#### Potential configuration

```hcl
cd_files = ["vendor-data"]
cd_content = {
  "meta-data" = jsonencode(local.instance_data)
  "user-data" = templatefile("user-data", { packages = ["nginx"] })
}
cd_label = "cidata"
```

#### Potential References
https://developer.hashicorp.com/packer/integrations/hashicorp/virtualbox/latest/components/builder/iso#cd-configuration

**Comment by jacobo-diaz** [comment]
Adding `floppy_content`would be a good idea too to be on par with other plugins!

**Comment by imranh2** [comment]
Just for awareness, I ditched Parallels for qemu because I didn't want to maintain a fork of this code. Also meant I could do x86_64 builds on my Apple Silicon machines.
