### ISSUE TITLE
Add support for configuring disk size in parallels-ipsw builder

### ISSUE THREAD

**Issue by johnbyrneio** [Parallels/packer-plugin-parallels#111]
#### Community Note

Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request.
If you are interested in working on this issue or have submitted a pull request, please leave a comment.

#### Description

Currently, the parallels-ipsw builder does not configure the VM's disk size. This results in the box size defaulting to 128 GB. Can an option be added to configure the size?

#### Use Case(s)

A clean macOS Sonoma install consumes about 23 GB of disk space. Reserving room for data, a disk size of 30-40GB would be relatively more manageable than the default 128GB.

#### Potential configuration

The same implementation as the parallels-iso builder will work here. 

1. Create VM and pass `--no-hdd` to `prlctl`
2. Call `stepCreateDisk` to create the new disk. `DiskSize` is already defined in the ipsw builder.

#### Contribute
If adding this feature makes sense, I'm happy to submit a PR.

**Comment by johnbyrneio** [comment]
I needed to implement this for a project I'm working on, so I submitted #112 for you to consider.

**Comment by bineesh-n** [comment]
Hi @johnbyrneio, this enhancement is not required if your PR for #109 is merged, right ?

**Comment by johnbyrneio** [comment]
Ideally both should be merged. That would match the functionality of the other builders.

#109 is enabling a user to execute any arbitrary`prlctl` commands using the `prlctl` field.
#111 is enabling a user to set the disk size using the `disk_size` field.
